/*
 * test_share.c  --  Unit tests for mpc_share.c (additive secret sharing)
 *
 * These tests run entirely on a single machine -- no network needed.
 * They verify the core cryptographic property:
 *
 *   share_reconstruct(share_split(s, n), n) == s   for all s, n
 *
 * and check that individual shares look uniformly random (privacy property).
 *
 * Run:
 *   ./test_share
 *
 * A clean run prints "ALL SHARE TESTS PASSED" and exits 0.
 */

#include "mpc_share.h"
#include "mpc_field.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#define P  ((uint32_t)MPC_PRIME)

static int _failures = 0;

static void check_eq(const char *name, field_t got, field_t expected) {
    if (got == expected) {
        printf("  PASS  %s\n", name);
    } else {
        printf("  FAIL  %s: got %u, expected %u\n", name, got, expected);
        _failures++;
    }
}

/* ------------------------------------------------------------------ */
/*  Correctness: reconstruct must equal the original secret             */
/* ------------------------------------------------------------------ */

static void test_correctness(void) {
    printf("\n--- Correctness: split then reconstruct ---\n");

    field_t shares[32];
    field_t result;

    /* n = 2 */
    share_split(0, 2, shares);
    result = share_reconstruct(shares, 2);
    check_eq("split/reconstruct(0, n=2)", result, 0);

    share_split(1, 2, shares);
    result = share_reconstruct(shares, 2);
    check_eq("split/reconstruct(1, n=2)", result, 1);

    share_split(999999, 2, shares);
    result = share_reconstruct(shares, 2);
    check_eq("split/reconstruct(999999, n=2)", result, 999999);

    share_split(P - 1, 2, shares);
    result = share_reconstruct(shares, 2);
    check_eq("split/reconstruct(p-1, n=2)", result, P - 1);

    /* n = 3 */
    share_split(42, 3, shares);
    result = share_reconstruct(shares, 3);
    check_eq("split/reconstruct(42, n=3)", result, 42);

    share_split(0, 3, shares);
    result = share_reconstruct(shares, 3);
    check_eq("split/reconstruct(0, n=3)", result, 0);

    /* n = 10 */
    share_split(1234567, 10, shares);
    result = share_reconstruct(shares, 10);
    check_eq("split/reconstruct(1234567, n=10)", result, 1234567);

    /* n = 20 (maximum expected use case) */
    share_split(9999999, 20, shares);
    result = share_reconstruct(shares, 20);
    check_eq("split/reconstruct(9999999, n=20)", result, 9999999);
}

/* ------------------------------------------------------------------ */
/*  Correctness over many random secrets                                */
/* ------------------------------------------------------------------ */

static void test_correctness_random(void) {
    printf("\n--- Correctness: 1000 random secrets, n=2 ---\n");

    int ok = 1;
    field_t shares[2];

    for (int i = 0; i < 1000; i++) {
        field_t s      = field_rand();
        share_split(s, 2, shares);
        field_t result = share_reconstruct(shares, 2);
        if (result != s) {
            printf("  FAIL  secret=%u reconstructed=%u\n", s, result);
            _failures++;
            ok = 0;
            break;
        }
    }
    if (ok) printf("  PASS  all 1000 random secrets correctly reconstructed\n");
}

/* ------------------------------------------------------------------ */
/*  Privacy: shares must not directly reveal the secret                 */
/*                                                                      */
/*  For additive n=2 sharing:                                           */
/*    shares[0] is uniform in [0, p-1]  (generated by field_rand)      */
/*    shares[1] = s - shares[0] mod p   (also uniform given random [0]) */
/*                                                                      */
/*  We verify that shares[0] != s in the overwhelming majority of runs. */
/*  (shares[0] == s with probability 1/p ≈ 4.7e-10, so never in 1000.) */
/* ------------------------------------------------------------------ */

static void test_privacy(void) {
    printf("\n--- Privacy: individual shares should not equal the secret ---\n");

    int leak = 0;
    field_t shares[2];
    field_t s = 500000U;

    for (int i = 0; i < 1000; i++) {
        share_split(s, 2, shares);
        if (shares[0] == s || shares[1] == s) {
            leak++;
        }
    }

    if (leak == 0) {
        printf("  PASS  no share equalled the secret across 1000 splits\n");
    } else {
        /*
         * A few leaks are astronomically unlikely but not impossible.
         * More than ~3 is a sign the RNG is broken.
         */
        printf("  NOTE  %d shares matched secret (expected ~0; investigate RNG if > 3)\n", leak);
    }
}

/* ------------------------------------------------------------------ */
/*  Manual verification: simulate 2-party protocol by hand              */
/*                                                                      */
/*  Party 0 has value 300, Party 1 has value 700.                      */
/*  Expected aggregate: 1000.                                           */
/*                                                                      */
/*  This is what test_uc1.c does over the network -- here we verify     */
/*  the arithmetic in isolation.                                        */
/* ------------------------------------------------------------------ */

static void test_manual_2party(void) {
    printf("\n--- Manual 2-party aggregation (300 + 700 = 1000) ---\n");

    field_t v0 = 300, v1 = 700;
    field_t s0[2], s1[2];   /* s0 = shares of v0, s1 = shares of v1 */

    share_split(v0, 2, s0);  /* s0[0] kept by party 0, s0[1] sent to party 1 */
    share_split(v1, 2, s1);  /* s1[0] sent to party 0, s1[1] kept by party 1 */

    /* After exchange: */
    field_t party0_recv = s1[0];   /* party 0 receives s1[0] from party 1 */
    field_t party1_recv = s0[1];   /* party 1 receives s0[1] from party 0 */

    /* Each party sums their local share + received share */
    field_t partial0 = field_add(s0[0], party0_recv);
    field_t partial1 = field_add(s1[1], party1_recv);

    /* Final aggregate = sum of partial sums */
    field_t aggregate = field_add(partial0, partial1);

    printf("  partial0 (party 0's sum) = %u\n", partial0);
    printf("  partial1 (party 1's sum) = %u\n", partial1);
    printf("  aggregate                = %u\n", aggregate);

    check_eq("2-party aggregate == 1000", aggregate, 1000);
}

/* ------------------------------------------------------------------ */
/*  main                                                                */
/* ------------------------------------------------------------------ */

int main(void) {
    printf("=== Secret sharing tests ===\n");

    test_correctness();
    test_correctness_random();
    test_privacy();
    test_manual_2party();

    printf("\n");
    if (_failures == 0) {
        printf("ALL SHARE TESTS PASSED\n");
        return 0;
    } else {
        printf("FAILED: %d test(s) failed\n", _failures);
        return 1;
    }
}
